name: waterbus_sdk
description: Flutter plugin of Waterbus. Build video call or online meeting application with SFU model. Supports iOS, Android.
version: 1.3.12
homepage: https://docs.waterbus.tech
publish_to: none

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Network
  connectivity_plus: ^6.0.2
  http: ^1.2.1
  dio: ^5.4.2+1
  dio_smart_retry: ^6.0.0
  dio_cache_interceptor: ^3.5.0
  socket_io_client: ^2.0.3+1

  # Storage
  hive: ^2.2.3

  # Utils
  collection: '>=1.16.0'
  universal_io: ^2.2.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  logger: ^2.3.0
  wakelock: ^0.6.2
  replay_kit_launcher: ^1.0.0
  flutter_callkit_incoming:
    git:
      url: https://github.com/waterbustech/flutter_callkit_incoming.git
      path: '.'
      ref: 2.0.0+4

  # WebRTC
  sdp_transform: ^0.3.2
  h264_profile_level_id: ^0.2.1
  flutter_webrtc_plus:
    # path: /Users/lambiengcode/Documents/webrtc/flutter-webrtc
    git:
      url: https://github.com/waterbustech/flutter-webrtc.git
      path: "."
      ref: 0.10.3+4

  # Dependency Injection
  get_it: ^7.6.8
  injectable: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Lints
  flutter_lints: ^4.0.0
  import_sorter: ^4.6.0

  # Code Generator
  injectable_generator: ^2.6.1
  build_runner: ^2.4.9
  mockito: ^5.4.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.waterbus.waterbus_sdk
        pluginClass: WaterbusSdkPlugin
      ios:
        pluginClass: WaterbusSdkPlugin
