name: CI

on:
  push:
    branches:
      - "*/*"
    tags:
      - "*"

jobs:
  test:
    name: 🛠 Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"
          cache: true
      - name: Dart Clean
        run: flutter clean
      - name: Install project dependencies
        run: flutter pub get
      - name: Dart Format Check
        run: dart format lib/ test/ --set-exit-if-changed
      - name: Import Sorter Check
        run: dart run import_sorter:main --no-comments --exit-if-changed
      - name: Dart Analyze Check
        run: flutter analyze
      - name: Dart Test Check
        run: flutter test